name: Publish Add-on
on: [push]  # Defines when the workflow runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Using a marketplace action
      - uses: actions/checkout@v3  # Common action to checkout code
      
      # Example using the Firefox add-on action shown in image
      - name: Publish Firefox Add-on
        uses: wdzeng/firefox-addon@v1.1.2
